#!/usr/bin/env bash

printf "%s" "🎵"
if [ "$(pactl get-sink-mute @DEFAULT_SINK@)" == "Mute: yes" ]; then
    printf "%s\n" "<span color=\"#ff4f4f\" weight=\"bold\">muted</span>"
else
    pactl get-sink-volume @DEFAULT_SINK@ | head -n1 | sed -r 's/^.* ([0-9]+%).*$/\1/'
fi
