#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"
export DENO_INSTALL="$(pwd)/deno/install"
export DENO_DIR="$(pwd)/deno/cache"
export DENO_VERSION=$(grep deno < .tool-versions | sed 's/deno\ //')
export DENO_BIN="${DENO_INSTALL}/bin/deno"
export SRK_OUT="$(pwd)/out"
export SRK_EXEC="srk"
export SRK_BIN="${SRK_OUT}/${SRK_EXEC}"
export SRK_INSTALL="/usr/local/bin"

function main {
  log "Ensuring Deno ${DENO_VERSION}"
  if [ ! -d "${DENO_INSTALL}" ]; then
    curl -fsSL "https://deno.land/x/install/install.sh" | sh -s "v${DENO_VERSION}"
  else
    "$DENO_BIN" upgrade --version "${DENO_VERSION}"
  fi

  log "Building srk"
  rm -rf "${SRK_OUT}"
  "$DENO_BIN" compile \
    -A --unstable \
    --import-map "src/cli/import_map.json" \
    --output "${SRK_BIN}" \
    "src/cli/main.ts"
  chmod +x "${SRK_BIN}"

  log "Installing srk on ${SRK_INSTALL}"
  sudo cp -f "${SRK_BIN}" "${SRK_INSTALL}"

  log "Running '${SRK_EXEC} install'"
  "${SRK_EXEC}" install
}

function log {
  printf "\e[1m\033[38;5;208m###\033[0m \e[1m%s\n\033[0m" "${1}"
}

main "${@}"
