#!/usr/bin/env bash
set -euo pipefail

export SRK_REPO="https://github.com/sirikon/workstation.git"
export SRK_ROOT=~/.srk
export SRK_EXEC="srk"
export SRK_INSTALL="/usr/local/bin"

function main {
  log "Ensuring repository on ${SRK_ROOT}"
  if [ ! -d "${SRK_ROOT}" ]; then
    git clone "${SRK_REPO}" "${SRK_ROOT}"
  fi
  cd "${SRK_ROOT}"

  log "Installing srk on ${SRK_INSTALL}"
  sudo mkdir -p "${SRK_INSTALL}"
  sudo rm -f "${SRK_INSTALL}/${SRK_EXEC}"

  log "Running '${SRK_EXEC} install'"
  "${SRK_EXEC}" install
}

function log {
  printf "\e[1m\033[38;5;208m###\033[0m \e[1m%s\n\033[0m" "${1}"
}

main
