#!/usr/bin/env bash

# Kudos to: https://unix.stackexchange.com/a/251920
#           https://www.reddit.com/r/i3wm/comments/7lr4zj/interactive_i3blocks/droclo7?utm_source=share&utm_medium=web2x

function main {
	case $BLOCK_BUTTON in
	1) pavucontrol &>/dev/null & ;;
	2) pactl set-sink-mute @DEFAULT_SINK@ toggle &>/dev/null ;;
	4) pactl set-sink-volume @DEFAULT_SINK@ +1% &>/dev/null ;;
	5) pactl set-sink-volume @DEFAULT_SINK@ -1% &>/dev/null ;;
	esac

	printf "%s" "🎵"
	muted=$(get-default-sink-muted)
	if [ "$muted" = "yes" ]; then
		printf "%s\n" "<span color=\"#ff4f4f\" weight=\"bold\">muted</span>"
		exit 0
	fi
	printf "%s\n" "$(get-default-sink-vol)"
}

function get-default-sink-vol {
	pacmd list-sinks |
		awk '/^\s+name: /{indefault = $2 == "<'"$(get-default-sink-name)"'>"}
            /^\s+volume: / && indefault {print $5; exit}'
}

function get-default-sink-muted {
	pacmd list-sinks |
		awk '/^\s+name: /{indefault = $2 == "<'"$(get-default-sink-name)"'>"}
            /^\s+muted: / && indefault {print $2; exit}'
}

function get-default-sink-name {
	pacmd stat | awk -F": " '/^Default sink name: /{print $2}'
}

main
