#!/usr/bin/env bash

if [ ! -f "/sys/class/power_supply/BAT0/capacity" ]; then
    exit 0
fi

charging="$(cat /sys/class/power_supply/AC/online)"
capacity="$(cat /sys/class/power_supply/BAT0/capacity)"

if [ "$charging" == "1" ]; then
    icon="⚡"
else
    icon="🔋"
fi

printf "%s" "${icon}${capacity}%"
